# Netlify configuration for LexLeaks Frontend (Next.js)

[build]
  # Build command for Next.js
  command = "npm run build"
  
  # Remove explicit publish directory - let Netlify handle it automatically for Next.js
  # publish = ".next"  # REMOVED - this was causing issues

[build.environment]
  # Your Google Cloud Run backend API URL
  NEXT_PUBLIC_API_URL = "https://lexleaks-api-563011146464.asia-south1.run.app"
  
  # Node version (optional but recommended)
  NODE_VERSION = "18"
  
  # Enable automatic deployments
  NETLIFY_USE_CACHE = "true"

# Essential plugin for Next.js on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Auto-deploy settings (ensure webhooks work)
[build.processing]
  skip_processing = false

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Serve static PWA files with proper headers
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-cache"

[[headers]]
  for = "/sw-custom.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-cache"

# Force serve static files before dynamic routing
[[redirects]]
  from = "/manifest.json"
  to = "/manifest.json"
  status = 200
  force = true

[[redirects]]
  from = "/sw.js"
  to = "/sw.js"
  status = 200
  force = true

[[redirects]]
  from = "/sw-custom.js"
  to = "/sw-custom.js"
  status = 200
  force = true

# Redirect CMS subdomain to admin dashboard
[[redirects]]
  from = "https://cms.lexleaks.com"
  to = "https://lexleaks.com/admin/dashboard"
  status = 301
  force = true

[[redirects]]
  from = "https://cms.lexleaks.com/*"
  to = "https://lexleaks.com/admin/:splat"
  status = 301
  force = true

# Redirect www to non-www
[[redirects]]
  from = "https://www.lexleaks.com/*"
  to = "https://lexleaks.com/:splat"
  status = 301
  force = true 