# Netlify configuration for LexLeaks Frontend (Next.js)

[build]
  # Build command for Next.js
  command = "npm run build"
  
  # Explicitly set publish directory for Next.js
  publish = ".next"

[build.environment]
  # Your Google Cloud Run backend API URL
  NEXT_PUBLIC_API_URL = "https://lexleaks-api-563011146464.asia-south1.run.app"
  
  # Node version (optional but recommended)
  NODE_VERSION = "18"

# Essential plugin for Next.js on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Redirect www to non-www (optional - adjust domain when you have it)
# [[redirects]]
#   from = "https://www.yourdomain.com/*"
#   to = "https://yourdomain.com/:splat"
#   status = 301
#   force = true 