apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    run.googleapis.com/build-enable-automatic-updates: 'false'
    run.googleapis.com/build-id: 14025051-5ec4-4ec1-a4ef-cde6bcec1c8d
    run.googleapis.com/build-image-uri: asia-south1-docker.pkg.dev/lexleaks/cloud-run-source-deploy/lexleaks-api
    run.googleapis.com/build-name: projects/563011146464/locations/asia-south1/builds/14025051-5ec4-4ec1-a4ef-cde6bcec1c8d
    run.googleapis.com/build-source-location: gs://run-sources-lexleaks-asia-south1/services/lexleaks-api/1751388002.612994-b2d10aae191248f58b1b80e4ab3dead6.zip#1751388002789817
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: '["https://lexleaks-api-563011146464.asia-south1.run.app","https://lexleaks-api-ordi4aqxlq-el.a.run.app"]'
  labels:
    cloud.googleapis.com/location: asia-south1
    run.googleapis.com/satisfiesPzs: 'true'
  name: lexleaks-api
  namespace: '563011146464'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '3'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 528.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
      labels:
        client.knative.dev/nonce: wcovsxdafx
        run.googleapis.com/startupProbeType: Default
    spec:
      containerConcurrency: 80
      containers:
      - env:
        - name: DATABASE_URL
          value: postgresql://postgres.xqnditvvoxuypkpayvtf:Pl2YfSm5eow2l6o8@aws-0-ap-south-1.pooler.supabase.com:6543/postgres
        - name: SECRET_KEY
          value: EV2UStmuxh1LhrUXH3-vyWeml-6FKHXDceCXvwzn4uo
        - name: ALGORITHM
          value: HS256
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: '30'
        - name: ADMIN_USERNAME
          value: admin
        - name: ADMIN_PASSWORD
          value: LexLeaks2024!
        - name: FRONTEND_URL
          value: https://glittery-dragon-d3e69b.netlify.app
        image: asia-south1-docker.pkg.dev/lexleaks/cloud-run-source-deploy/lexleaks-api@sha256:67f8c246152493cca9395a3d698e08e3c9551e7cff8b491f029ecdffa4f6a9c0
        ports:
        - containerPort: 8080
          name: http1
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
        startupProbe:
          failureThreshold: 1
          periodSeconds: 240
          tcpSocket:
            port: 8080
          timeoutSeconds: 240
      serviceAccountName: 563011146464-compute@developer.gserviceaccount.com
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
